#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# ROS related aliases
alias cm='cd "$ROS_WORKSPACE"; catkin_make\'
alias cb='cd "$ROS_WORKSPACE"; catkin build\'
# alias cb='cd "$ROS_WORKSPACE"; catkin build --cmake-args -DPYTHON_VERSION=3.6\'
alias ss='source "$ROS_WORKSPACE"/devel/setup.bash\'
alias tl='rostopic list'
alias te='rostopic echo'
alias th='rostopic hz'
alias sl='rosservice list'
alias sc='rosservice call'
alias mi='rosmsg info'
alias si='rossrv info'
alias ros_dep_install='rosdep install --from-paths src --ignore-src -r -y'
